=== bmc-toolbox/redfish-mocks/mocks/hpegen10/redfish/v1/SchemaStore/en/HpeiLOGUIService.json/index.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "copyright": "Copyright 2014-2018 Hewlett Packard Enterprise Development, LP.  Portions Copyright 2014-2016 Distributed Management Task Force. All rights reserved.",
    "properties": {
        "@odata.context": {
            "$ref": "Resource.json#/definitions/odatacontext"
        },
        "@odata.etag": {
            "$ref": "Resource.json#/definitions/odataetag"
        },
        "@odata.id": {
            "$ref": "Resource.json#/definitions/odataid"
        },
        "@odata.type": {
            "$ref": "Resource.json#/definitions/odatatype"
        },
        "Description": {
            "$ref": "Resource.json#/definitions/Description"
        },
        "Id": {
            "$ref": "Resource.json#/definitions/Id"
        },
        "Name": {
            "$ref": "Resource.json#/definitions/Name"
        },
        "TreeList": {
            "description": "An ordered sequence of freeze-dried task items that iLO can iterate and schedule.",
            "items": {
                "additionalProperties": false,
                "properties": {
                    "Features": {
                        "description": "Command to execute.",
                        "readonly": false,
                        "type": "string"
                    },
                    "LangKey": {
                        "longDescription": "The value of this property shall be the unique identifier for the resource and it shall be of the form defined in the SPMF specification.",
                        "readonly": true,
                        "type": "string"
                    },
                    "Link": {
                        "longDescription": "The value of this property shall be the unique identifier for the resource and it shall be of the form defined in the SPMF specification.",
                        "readonly": true,
                        "type": "string"
                    },
                    "RightHandMenu": {
                        "description": "Name of the component.",
                        "readonly": false,
                        "type": "string"
                    },
                    "TabSet": {
                        "description": "The unique filename of the component.  This correlates to 'Filename' in the HpeComponent.",
                        "readonly": false,
                        "type": "string"
                    },
                    "Text": {
                        "description": "Command to execute.",
                        "readonly": false,
                        "type": "string"
                    },
                    "Tabs": {
                        "description": "This is an unordered set of permitted updaters that can execute this item.",
                        "items": {
                            "additionalProperties": false,
                            "properties": {
                                "Features": {
                                    "description": "Name of the component.",
                                    "readonly": false,
                                    "type": "string"
                                },
                                "LangKey": {
                                    "longDescription": "The value of this property shall be the unique identifier for the resource and it shall be of the form defined in the SPMF specification.",
                                    "readonly": true,
                                    "type": "string"
                                },
                                "Link": {
                                    "description": "The unique filename of the component.  This correlates to 'Filename' in the HpeComponent.",
                                    "readonly": false,
                                    "type": "string"
                                },
                                "Text": {
                                    "description": "Command to execute.",
                                    "readonly": false,
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "readonly": false,
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "readonly": false,
            "type": "array"
        }
    },
    "title": "#HpeiLOGUIService.v1_0_0.HpeiLOGUIService",
    "type": "object"
}

=== bmc-toolbox/redfish-mocks/mocks/hpegen10/redfish/v1/Managers/1/GUIService/index.json
{
    "@odata.context": "/redfish/v1/$metadata#HpeiLOGUIService.HpeiLOGUIService",
    "@odata.etag": "W/\"5B368DA2\"",
    "@odata.id": "/redfish/v1/Managers/1/GUIService/",
    "@odata.type": "#HpeiLOGUIService.v1_0_0.HpeiLOGUIService",
    "Id": "GUIService",
    "Description": "iLO GUI Service",
    "Name": "GUI Service",
    "TreeList": [
        {
            "LangKey": "info",
            "TabSet": "information",
            "Tabs": [
                {
                    "LangKey": "overview",
                    "Link": "summary.html",
                    "Text": "Overview"
                },
                {
                    "LangKey": "sessions",
                    "Link": "info_sessions.html",
                    "Text": "Session List"
                },
                {
                    "LangKey": "iLOLog",
                    "Link": "info_log.html",
                    "Text": "iLO Event Log"
                },
                {
                    "LangKey": "iml",
                    "Link": "info_iml.html",
                    "Text": "Integrated Management Log"
                },
                {
                    "LangKey": "ers_nav_tab_bb",
                    "Link": "admin_ers_bb.html",
                    "Text": "Active Health System Log"
                },
                {
                    "LangKey": "diag",
                    "Link": "info_diagnostics.html",
                    "Text": "Diagnostics"
                },
                {
                    "LangKey": "discoveryServices",
                    "Link": "info_discovery.html",
                    "Text": "Discovery Services"
                }
            ],
            "Text": "Information"
        },
        {
            "LangKey": "sysInfo",
            "TabSet": "sysInfo",
            "Tabs": [
                {
                    "LangKey": "summary",
                    "Link": "info_system.html",
                    "Text": "Summary"
                },
                {
                    "LangKey": "proc",
                    "Link": "info_system_proc.html",
                    "Text": "Processors"
                },
                {
                    "LangKey": "mem",
                    "Link": "info_system_mem.html",
                    "Text": "Memory"
                },
                {
                    "LangKey": "nic",
                    "Link": "info_system_nic.html",
                    "Text": "Network"
                },
                {
                    "LangKey": "inventory",
                    "Link": "info_system_inventory.html",
                    "Text": "Device Inventory"
                },
                {
                    "LangKey": "storage",
                    "Link": "info_system_drives.html",
                    "Text": "Storage"
                }
            ],
            "Text": "System Information"
        },
        {
            "LangKey": "firmware",
            "RightHandMenu": "fw_sw_rhMenu.html",
            "TabSet": "firmware",
            "Tabs": [
                {
                    "LangKey": "FwInfo",
                    "Link": "fw_sw_firmware.html",
                    "Text": "Firmware"
                },
                {
                    "LangKey": "software",
                    "Link": "fw_sw_software.html",
                    "Text": "Software"
                },
                {
                    "LangKey": "maintenanceWindows",
                    "Link": "fw_sw_MaintenanceWindows.html",
                    "Text": "Maintenance Windows"
                },
                {
                    "LangKey": "repo",
                    "Link": "fw_sw_iLORepo.html",
                    "Text": "iLO Repository"
                },
                {
                    "LangKey": "installSets",
                    "Link": "fw_sw_InstallSets.html",
                    "Text": "Install Sets"
                },
                {
                    "LangKey": "installationQueue",
                    "Link": "fw_sw_InstallationQueue.html",
                    "Text": "Installation Queue"
                }
            ],
            "Text": "Firmware & OS Software"
        },
        {
            "Features": "federation",
            "LangKey": "fed",
            "TabSet": "federation",
            "Tabs": [
                {
                    "LangKey": "setup",
                    "Link": "admin_multi_config.html",
                    "Text": "Setup"
                },
                {
                    "LangKey": "moverview",
                    "Link": "multi_summary.html",
                    "Text": "Multi-System View"
                },
                {
                    "LangKey": "mnodemap",
                    "Link": "multi_nodemap.html",
                    "Text": "[Debug] Multi-System Map"
                },
                {
                    "LangKey": "mvm",
                    "Link": "multi_vm.html",
                    "Text": "Group Virtual Media"
                },
                {
                    "LangKey": "mPwr",
                    "Link": "multi_power.html",
                    "Text": "Group Power"
                },
                {
                    "LangKey": "mPwrSettings",
                    "Link": "multi_power_settings.html",
                    "Text": "Group Power Settings"
                },
                {
                    "LangKey": "mfirmware",
                    "Link": "multi_firmware.html",
                    "Text": "Group Firmware Update"
                },
                {
                    "LangKey": "mlicense",
                    "Link": "multi_license.html",
                    "Text": "Group Licensing"
                },
                {
                    "LangKey": "mconfig",
                    "Link": "multi_config.html",
                    "Text": "Group Configuration"
                }
            ],
            "Text": "iLO Federation"
        },
        {
            "LangKey": "rc",
            "TabSet": "rc",
            "Tabs": [
                {
                    "LangKey": "launch",
                    "Link": "rc_info.html",
                    "Text": "Launch"
                },
                {
                    "LangKey": "vm",
                    "Link": "vm.html",
                    "Text": "Virtual Media"
                },
                {
                    "LangKey": "hotKey",
                    "Link": "rc_hotkeys.html",
                    "Text": "Hot Keys"
                },
                {
                    "LangKey": "security",
                    "Link": "admin_security_remote.html",
                    "Text": "Security"
                }
            ],
            "Text": "Remote Console & Media"
        },
        {
            "Features": "power_management",
            "LangKey": "pwrMgmt",
            "TabSet": "pwrMgmt",
            "Tabs": [
                {
                    "LangKey": "pwrServer",
                    "Link": "power_server.html",
                    "Text": "Server Power"
                },
                {
                    "LangKey": "pwrMeter",
                    "Link": "power_meter.html",
                    "Text": "Power Meter"
                },
                {
                    "LangKey": "pwrSettings",
                    "Link": "power_settings.html",
                    "Text": "Power Settings"
                },
                {
                    "LangKey": "pwr",
                    "Link": "info_system_power.html",
                    "Text": "Power"
                },
                {
                    "LangKey": "fans",
                    "Link": "info_system_fans.html",
                    "Text": "Fans"
                },
                {
                    "LangKey": "temp",
                    "Link": "info_system_temps.html",
                    "Text": "Temperatures"
                }
            ],
            "Text": "Power & Thermal"
        },
        {
            "Features": "system_tuning",
            "LangKey": "IST",
            "Link": "perf_settings.html",
            "Text": "Intelligent System Tuning"
        },
        {
            "Features": "dedicated_nic",
            "LangKey": "dedicateNIC",
            "TabSet": "net0",
            "Tabs": [
                {
                    "LangKey": "summary",
                    "Link": "network_summary.html?intf=0",
                    "Text": "Summary"
                },
                {
                    "LangKey": "general",
                    "Link": "network_general.html?intf=0",
                    "Text": "General"
                },
                {
                    "LangKey": "ipv4",
                    "Link": "network_ipv4.html?intf=0",
                    "Text": "IPv4"
                },
                {
                    "LangKey": "ipv6",
                    "Link": "network_ipv6.html?intf=0",
                    "Text": "IPv6"
                },
                {
                    "LangKey": "sntp",
                    "Link": "network_sntp.html?intf=0",
                    "Text": "SNTP"
                }
            ],
            "Text": "iLO Dedicated Network Port"
        },
        {
            "LangKey": "ers_nav_tab",
            "TabSet": "ers",
            "Tabs": [
                {
                    "LangKey": "ers_nav_tab_reg",
                    "Link": "admin_ers_cfg_d.html",
                    "Text": "Registration"
                },
                {
                    "LangKey": "ers_nav_tab_se",
                    "Link": "admin_ers_se.html",
                    "Text": "Service Events"
                },
                {
                    "LangKey": "ers_nav_tab_data",
                    "Link": "admin_ers_dc.html",
                    "Text": "Data Collections"
                }
            ],
